/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.CidadeDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class TelaPesquisaCidade extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaCidade
     */
    String Cod, Cidade;

    public TelaPesquisaCidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        MostrarCidades();
        jTCidade.setRowSelectionInterval(0,0);
    }

    public void MostrarCidades() {
        jTCidade.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTCidade.getColumnModel().getColumn(1).setPreferredWidth(300);
        DefaultTableModel modelo = (DefaultTableModel) jTCidade.getModel();
        modelo.setNumRows(0);
        CidadeDao cdao = new CidadeDao();

        cdao.MostrarCidade().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCod_cidade(),
                c.getNome_cidade()
            });
        });
    }

    public void MostrarBuscaCodigo(int cod_cidade) {
        jTCidade.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTCidade.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTCidade.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTCidade.getColumnModel().getColumn(3).setPreferredWidth(60);
        DefaultTableModel modelo = (DefaultTableModel) jTCidade.getModel();
        modelo.setNumRows(0);
        CidadeDao cdao = new CidadeDao();

        cdao.BuscaCidadeCodigo(cod_cidade).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCod_cidade(),
                c.getNome_cidade()
            });
        });
    }

    public void MostrarBuscaNome(String nome_cidade) {
        jTCidade.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTCidade.getColumnModel().getColumn(1).setPreferredWidth(300);
        DefaultTableModel modelo = (DefaultTableModel) jTCidade.getModel();
        modelo.setNumRows(0);
        CidadeDao cdao = new CidadeDao();

        cdao.BuscaCidadeNome(nome_cidade).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCod_cidade(),
                c.getNome_cidade()
            });
        });
    }

    public void Consultar() {
        if (jRCodigo.isSelected()) {
            if (TxtConsulta.getText() == null || TxtConsulta.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo código, é obrigatório para a consulta !!");
                TxtConsulta.requestFocus();
            } else {
                MostrarBuscaCodigo(Integer.parseInt(TxtConsulta.getText()));
            }
        } else if (jRNOme.isSelected()) {
            MostrarBuscaNome(TxtConsulta.getText());
        }
    }

    /**
     *
     * @param event
     * @param x
     * @param y
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCidade = new javax.swing.JTable();
        jRCodigo = new javax.swing.JRadioButton();
        jRNOme = new javax.swing.JRadioButton();
        TxtConsulta = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N

        jTCidade.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jTCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome"
            }
        ));
        jTCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCidadeMouseClicked(evt);
            }
        });
        jTCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCidadeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTCidade);

        jRCodigo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRCodigo.setText("Código");

        jRNOme.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRNOme.setText("Nome");

        TxtConsulta.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        TxtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConsultaActionPerformed(evt);
            }
        });

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRNOme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConsultar)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCodigo)
                    .addComponent(jRNOme)
                    .addComponent(TxtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConsultaActionPerformed
        Consultar();
    }//GEN-LAST:event_TxtConsultaActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        Consultar();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCidadeMouseClicked

        if (jTCidade.getSelectedRow() != -1) {
            Cod = (jTCidade.getValueAt(jTCidade.getSelectedRow(), 0).toString());
            Cidade = (jTCidade.getValueAt(jTCidade.getSelectedRow(), 1).toString());
            int i = JOptionPane.showConfirmDialog(this, "Confirma a Cidade: " + Cidade);
            if (i == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTCidadeMouseClicked

    private void jTCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Cod = (jTCidade.getValueAt(jTCidade.getSelectedRow(), 0).toString());
            Cidade = (jTCidade.getValueAt(jTCidade.getSelectedRow(), 1).toString());
            int i = JOptionPane.showConfirmDialog(this, "Confirma a Cidade: " + Cidade);
            if (i == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTCidadeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisaCidade dialog = new TelaPesquisaCidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtConsulta;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRCodigo;
    private javax.swing.JRadioButton jRNOme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCidade;
    // End of variables declaration//GEN-END:variables
}
