/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.BairroDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte T.I
 */
public class TelaPesquisaBairro extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaBairro
     */
    String Cod, Bairro;

    public TelaPesquisaBairro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CarregarTabela();
        jTBairro.setRowSelectionInterval(0,0);
    }

    public void CarregarTabela() {
        jTBairro.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTBairro.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(3).setPreferredWidth(100);
        DefaultTableModel modelo = (DefaultTableModel) jTBairro.getModel();
        modelo.setNumRows(0);
        BairroDao bdao = new BairroDao();

        bdao.MostrarBairro().forEach((b) -> {
            modelo.addRow(new Object[]{
                b.getCod_bairro(),
                b.getDesc_bairro(),
                b.getCod_cidade(),
                b.getNome_cidade()
            });
        });
    }

    public void MostrarBairroCodigo(int codigo) {
        jTBairro.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTBairro.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(3).setPreferredWidth(100);
        DefaultTableModel modelo = (DefaultTableModel) jTBairro.getModel();
        modelo.setNumRows(0);
        BairroDao bdao = new BairroDao();

        bdao.MostrarBairroCodigo(codigo).forEach((b) -> {
            modelo.addRow(new Object[]{
                b.getCod_bairro(),
                b.getDesc_bairro(),
                b.getCod_cidade(),
                b.getNome_cidade()
            });
        });
    }

    public void MostrarBairroNome(String nome) {
        jTBairro.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTBairro.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTBairro.getColumnModel().getColumn(3).setPreferredWidth(100);
        DefaultTableModel modelo = (DefaultTableModel) jTBairro.getModel();
        modelo.setNumRows(0);
        BairroDao bdao = new BairroDao();

        bdao.MostrarBairroNome(nome).forEach((b) -> {
            modelo.addRow(new Object[]{
                b.getCod_bairro(),
                b.getDesc_bairro(),
                b.getCod_cidade(),
                b.getNome_cidade()
            });
        });
    }

    public void LimparCampos() {
        txtConsulta.setText("");
    }

    public void Consultar() {
        if (jRCodigo.isSelected()) {
            MostrarBairroCodigo(Integer.parseInt(txtConsulta.getText()));
            LimparCampos();
        } else if (jRNome.isSelected()) {
            MostrarBairroNome(txtConsulta.getText());
            LimparCampos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBairro = new javax.swing.JTable();
        jRCodigo = new javax.swing.JRadioButton();
        jRNome = new javax.swing.JRadioButton();
        txtConsulta = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bairros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jTBairro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Bairro", "Código Cidade", "Nome Cidade"
            }
        ));
        jTBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBairroMouseClicked(evt);
            }
        });
        jTBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBairroKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTBairro);

        buttonGroup1.add(jRCodigo);
        jRCodigo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRCodigo.setText("Código");
        jRCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCodigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRNome);
        jRNome.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRNome.setText("Nome");
        jRNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNomeActionPerformed(evt);
            }
        });

        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaKeyPressed(evt);
            }
        });

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConsultar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCodigo)
                    .addComponent(jRNome)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Consultar();
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        Consultar();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBairroMouseClicked
        if (jTBairro.getSelectedRow() != -1) {
            Cod = (jTBairro.getValueAt(jTBairro.getSelectedRow(), 0).toString());
            Bairro = (jTBairro.getValueAt(jTBairro.getSelectedRow(), 1).toString());
            int i = JOptionPane.showConfirmDialog(this, "Confirma a Bairro: " + Bairro);
            if (i == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTBairroMouseClicked

    private void txtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Consultar();
        }
    }//GEN-LAST:event_txtConsultaKeyPressed

    private void jTBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBairroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Cod = (jTBairro.getValueAt(jTBairro.getSelectedRow(), 0).toString());
            Bairro = (jTBairro.getValueAt(jTBairro.getSelectedRow(), 1).toString());
            int i = JOptionPane.showConfirmDialog(this, "Confirma a Bairro: " + Bairro);
            if (i == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTBairroKeyPressed

    private void jRNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNomeActionPerformed
        CarregarTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_jRNomeActionPerformed

    private void jRCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCodigoActionPerformed
        CarregarTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_jRCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisaBairro dialog = new TelaPesquisaBairro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRCodigo;
    private javax.swing.JRadioButton jRNome;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTBairro;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
